### ISSUE TITLE
Uji Coba Flow end to end As Petugas Kabupaten

### ISSUE THREAD

**Issue by escape-dev** [tuanpembual/pengaduan-masyarakat#24]
A. Login 
1. Ketika user menginputkan username petugas dengan password yang tidak benar maka akan muncul pesan `Username atau Password salah! petugas`
    - User menginputkan username dan password
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/922835f1-f28f-4654-811c-688ac4bb831e)

    - User mengeklik tombol login
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/28844b8c-7a28-47b2-8d99-bb68fc2b6e06)

status: ok

2. Ketika user menginputkan username dan password petugas dengan benar maka akan langsung di redirect ke halaman petugas
    - User menginputkan username dan password 
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/da7f0519-1b9f-4574-9d3c-7eec2bf6452d)

    - User mengeklik tombol login
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/fda3005a-2c5e-49a7-82c6-d8576e97a8bb)

status: ok

**Comment by escape-dev** [comment]
### B. Pengaduan Masuk
1. Petugas dapat melihat pengaduan masuk 
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/6cb3d256-1100-49ad-a56f-37f4a6f19d91)

status: ok

2. Petugas dapat melihat detail pengaduan
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/e30e7b3b-0dfa-43d5-aab4-32864f5c8a77)

status: ok

3. Petugas dapat memroses pengaduan
    - Petugas mengisi form tanggapan
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/e30e7b3b-0dfa-43d5-aab4-32864f5c8a77)

    - Petugas melakukan klik pada tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/d0be6338-ff40-4223-9473-8c8c22a69ed3)

status: ok

4. Petugas dapat menolak pengaduan
    - Petugas mengisi form tanggapan
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/153fc429-4f07-44ab-b702-fedeca6ff922)

    - Petugas melakukan klik pada tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/d57964bb-05d8-4e2b-b354-4e259f42b1cb)

status: ok

**Comment by escape-dev** [comment]
### C. Pengaduan di Proses
1. Petugas dapat melihat pengaduan yang sedang diproses
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/5531014f-b98d-494f-bf8f-9065a80eca81)

status: ok

2. Petugas dapat merubah status pengaduan dari proses menjadi selesai
    - petugas mengeklik tombol selesai
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/ba2a1d3c-dc5d-479d-a966-6739eb785fe1)

status: ok

**Comment by escape-dev** [comment]
### D. Pengaduan Ditolak
1. Petugas dapat melihat pengaduan yang ditolak
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/aa89b1d0-6970-4c31-98bd-c68b1bca1a3c)

**Comment by escape-dev** [comment]
### E. Pengaduan Selesai
1. Petugas dapat melihat pengaduan yang sudah selesai
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/11470fae-a98a-4f55-aa2d-c632373d5e29)

**Comment by MHafizAF** [comment]
Untuk flow dari petugas kabupaten sudah ok mas @tuanpembual

**Comment by escape-dev** [comment]
F. Generate Laporan
1. Petugas dapat membuat laporan dari data pengaduan yang masuk
    - Petugas melakukan klik pada tombol priview or download 
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/b5fa1c28-e199-4726-a570-f43394945444)

status: ok

**Comment by escape-dev** [comment]
Overall untuk flow end to end as petugas sudah ok mas @tuanpembual

**Comment by tuanpembual** [comment]
kepikiran, 
![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/922635/4f7700ff-c3ec-4a75-8614-fad827184779)

gambarnya peyang yak. semacam ketarik kesamping.

Posible kita fix @MHafizAF ?

**Comment by escape-dev** [comment]
> 

kalau gambar saya kurang bisa mas @tuanpembual kwkw, mungkin mas @Ilham-muttaqien17 bisa nanti saya hubungi

**Comment by tuanpembual** [comment]
noted, Rabu siang kita diskusi di kantor, bahas
* CV related
* Serverity and Priority

**Comment by Ilham-muttaqien17** [comment]
Oke mas

**Comment by escape-dev** [comment]
> 

siap mas

**Comment by tuanpembual** [comment]
@MHafizAF @Ilham-muttaqien17 saya nemu improvement lagi ( terakhir).

punya ide g? 
![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/922635/ec4ed480-24ba-4c61-85bd-22eaa70a3eea)

baiknya info apa aja yg ditampilkan?

saat ini cuma, laporan, telpon, pengaduan. tidak banyak bermanfaat :D

**Comment by escape-dev** [comment]
kalau menurut saya itu, ditambahkan jenis laporan sama, lokasi mas @tuanpembual

**Comment by tuanpembual** [comment]
bisa dieksekusi @MHafizAF ? :D

**Comment by escape-dev** [comment]
@tuanpembual bisa mas, berarti ditambahkan jenis laporan sama lokasi ya mas

**Comment by escape-dev** [comment]
### Gambar
Untuk dari gambar overall udah ok mas, sudah tidak peyang.
![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/25b44050-0984-4caa-a2e7-bd3547c6a007)

**Comment by escape-dev** [comment]
jadinya seperti ini mas @tuanpembual kalau sudah ditambahkan informasi jenis laporan sama lokasi kejadian mas

![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/071ec9c7-ec0b-49dc-9b8a-1c8709ae983e)

**Comment by tuanpembual** [comment]
GTG (go to go) @MHafizAF 
bisa ajuin PR aja.

**Comment by escape-dev** [comment]
@tuanpembual siap mas.

sudah saya buat pr.nya mas #31

**Comment by escape-dev** [comment]
> @MHafizAF @Ilham-muttaqien17 saya nemu improvement lagi ( terakhir).
> 
> punya ide g? ![image](https://user-images.githubusercontent.com/922635/248169269-ec4ed480-24ba-4c61-85bd-22eaa70a3eea.png)
> 
> baiknya info apa aja yg ditampilkan?
> 
> saat ini cuma, laporan, telpon, pengaduan. tidak banyak bermanfaat :D

Untuk bagian card pengaduan sudah ada informasi terbaru yaitu lokasi dan jenis pengaduan mas @tuanpembual.
![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/554a2bb9-6349-49ed-8c31-3520dc6028d2)

Untuk overall sudah ok mas.

**Comment by tuanpembual** [comment]
noted @MHafizAF 

lagi trimming db migrate sama translasi
