### ISSUE TITLE
Uji Coba Flow end to end As Petugas Provinsi

### ISSUE THREAD

**Issue by escape-dev** [tuanpembual/pengaduan-masyarakat#25]
### A. Login
1. Ketika petugas melakukan login dengan username dan password yang salah maka akan muncul pesan `Username atau Pasword salah! petugas`
    - Petugas menginputkan username dan password
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/61e4a79a-bb08-4212-b4c9-a8571d5df68a)

    - Petugas mengeklik tombol login
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/64e48dc4-8914-49cc-bd2f-620757b35b58)

status: ok

2. Ketika petugas melakukan login dengan username dan password yang benar maka akan di redirect ke halaman petugas
    - Petugas menginputkan username dan password 
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/f6b1fdbc-0916-4f67-b37d-f471deec18a0)

    - Petugas mengeklik tombol login
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/076d4fe7-68bb-44e2-8ce7-66d31132ee89)

status: ok

**Comment by escape-dev** [comment]
### B. Pengaduan Masuk
1. Petugas dapat melihat semua pengaduan masuk
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/c51cf019-fdef-47a0-b9b0-b99a7ed2e9ee)

status: ok

2. Petugas dapat melihat detail pengaduan 
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/61387fb5-0dbe-4763-9d3d-4e435a6b9049)

status: ok

3. Petugas dapat memproses pengaduan yang masuk
    - Petugas mengisikan form tanggapan
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/69752eee-b6a1-41b0-9d85-ab57ef89d8a7)

    - Petugas mengeklik tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/5e397197-a055-4981-a210-2f678d804976)

status: ok

4. Petugas dapat menolak pengaduan yang masuk
    - Petugas mengisikan form tanggapan
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/eb5045c6-92dd-4481-bc00-30cfafb592f9)

    - Petugas mengeklik tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/1e379065-0e46-4be8-a694-e306fa331aa7)

status: ok

**Comment by escape-dev** [comment]
### C. Pengaduan Diproses
1. Petugas dapat melihat pengaduan yang sedang di proses
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/d17a9e28-cb17-4d2e-b80f-fc399a3fba18)

status: ok

2. Petugas dapat merubah status dari diproses menjadi selesai
    - Petugas melakukan klik tombol selesai pada salah satu pengaduan
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/02a39960-1e20-45bf-a7b6-6f76a4e7b69f)

status: ok

**Comment by escape-dev** [comment]
### D. Pengaduan Ditolak
1. Petugas dapat melihat semua pengaduan yang ditolak
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/1df7db93-40d1-40ad-97a2-6e87fba0cd44)

status: ok

**Comment by escape-dev** [comment]
### E. Pengaduan Selesai
1. Petugas dapat melihat pengaduan yang sudah selesai
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/2ac0c8ea-8eef-47a7-b7e6-7912ab244b4e)

status: ok

**Comment by escape-dev** [comment]
### F. Generate Laporan
1. Petugas dapat melakukan generate laporan
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/03af95e4-63c0-444d-bc99-be9e3761cec1)

**Comment by escape-dev** [comment]
Overall untuk uji coba end to end untuk petugas provinsi sudah ok mas @tuanpembual

**Comment by tuanpembual** [comment]
Noted @MHafizAF 

issue ini bisa ditutup.
