### ISSUE TITLE
Uji Coba Flow end to end As Admin

### ISSUE THREAD

**Issue by escape-dev** [tuanpembual/pengaduan-masyarakat#26]
### A. Login
1. Ketika user menginputkan username dan password yang salah maka muncul pesan `Username atau password salah!`
    - User menginputkan username dan password
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/35cfe597-e3ed-4177-8268-1db62fa167f4)

    - User mengeklik tombol login
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/0febea99-b107-4130-99a4-cab2edad7d29)

status: ok

2. Ketika user menginputkan username dan password yang benar maka akan di redirect ke halaman admin
    - User menginputkan username dan password
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/5a3229c1-ee54-4b6f-bc79-3fc1f8b91ac0)

    - User mengeklik tombol login
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/033efbf4-994c-4ac9-8b7e-ed7c32504519)

status: ok

**Comment by escape-dev** [comment]
### B. Menambah Petugas
1. Ketika user tidak mengisi form dan langsung mengeklik tombol submit maka akan muncul pesan validasi
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/0b7cd412-ff25-4937-a0a2-bf13bb2c7118)

status: ok

2. Ketika user menginputkan username yang sudah ada maka akan muncul pesan `Username ini sudah terdaftar ada`
    - User mengisikan form
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/6a0154bd-e6b0-4b53-92c8-5b5d22ad08a1)

    - User mengeklik tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/ee6d3dab-198c-4ea4-9b49-4e356da91565)

status: ok

3. Ketika user menginputkan semua form dengan benar maka akan muncul pesan `Buat akun petugas berhasil`
    - User mengisikan form 
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/0d6cb4db-1171-4472-bea7-08df6cc88187)

    - User mengeklik tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/af65e5ed-12c2-4032-8192-eb7133e5f6ba)

status: ok

**Comment by escape-dev** [comment]
### C. Admin dapat Melihat Semua Akun Petugas
![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/1a614a40-62da-4279-818f-40b1a4c32fa8)

status: ok

**Comment by escape-dev** [comment]
### D. Update Petugas
oh iya mas @tuanpembual untuk update petugas ini nanti bisa merubah level atau tidak?

kalau bisa update level kemungkinan nanti merubah flow dari update petugas dikarenakan untuk petugas dengan level admin tidak memiliki kabupaten sedangkan untuk level petugas harus memiliki kabupaten. 
Jadi nanti harus menambahkan form kabupaten di halaman edit petugas. Dan itu nanti mungkin agak tricky karena ketika user sebelumnya admin dan mau dirubah menjadi petugas harus melakukan set kabupaten terlebih dahulu.

**Comment by tuanpembual** [comment]
set aja tidak bisa ya.

tq

**Comment by MHafizAF** [comment]
> 

di set bagaimana ya mas?

**Comment by escape-dev** [comment]
di set bagaimana ya mas?

**Comment by tuanpembual** [comment]
maksudnya flow dibuat as it saat ini. tidak ada yg perlu diubah.

apakah testing nya berhasil?

**Comment by escape-dev** [comment]
@tuanpembual kalau agar flow tidak berubah menurut saya harus menghilangkan form level. Karena untuk level ini sangat berpengaruh di fitur fitur lain seperti tanggapan mas.

Tapi kalau untuk edit petugas sendiri tidak ada masalah, namun masalah nanti ditemukan di saat merubah dari admin menjadi petugas, itu nanti berpengaruhnya di bagian tanggapan mas.

**Comment by escape-dev** [comment]
mas @tuanpembual apakah jadi ke kantor mas?

**Comment by escape-dev** [comment]
### D. Update Petugas
1. Ketika user mengosongkan form maka akan terkena validasi dan memunculkan pesan validasi
    - User mengosongkan form
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/5f58e61d-c842-47e8-a397-76f76305ce86)

    - User mengeklik tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/cbd50f70-ea70-4785-8025-9b8001d62570)

status: ok

2. Ketika user menganti isi form nama, telp dan level maka akan muncul pesan `Akun petugas berhasil diedit`
    - User merubah isi form 
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/cb17d106-e759-4e3b-b9db-a3bb6ab03749)

    - User mengeklik tombol submit
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/9ad49d75-765a-42b2-810b-d5c60beb7764)

status: ok

**Comment by escape-dev** [comment]
### E. Konfirmasi Akun Masyarakat
1. Admin dapat melihat semua akun masyarakat
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/ba66688b-9eeb-4dad-9df8-d59d63ecd717)

status: ok

2. Admin dapat merubah status verifikasi menjadi aktif atau nonaktif
    - Admin merubah status menjadi nonaktif
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/61c51c51-4cfa-488b-b5d2-fa3710dceff5)

    - Admin dapat merubah status dari nonaktif menjadi aktif
       ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/018e8d53-e612-4f60-b76a-6bc60ec90a3d)

status: ok

**Comment by escape-dev** [comment]
Untuk overall flow as admin aman mas @tuanpembual

**Comment by tuanpembual** [comment]
LGTM.

issue ini sdh bisa ditutup
