### ISSUE TITLE
Fix gambar card pengaduan

### ISSUE THREAD

**Issue by Ilham-muttaqien17** [tuanpembual/pengaduan-masyarakat#29]
Mas @tuanpembual , aku udah nyoba buat benerin gambar di card pengaduan biar gk penyok, kurang lebih hasilnya kayak gini

![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75342298/0467c029-2ed8-4aa8-987a-e50d8bbb0457)

Tapi buat card yang gk kedetek gambarnya malah ngebuat cardnya jadi gk sama ukurannnya kayak gambar di atas. Gimana menurut mas?

**Comment by tuanpembual** [comment]
kita coba dulu di server ya @Ilham-muttaqien17

**Comment by Ilham-muttaqien17** [comment]
Oke mas, nanti saya buat pull request dulu.

**Comment by tuanpembual** [comment]
sudah saya deploy, mohon dicek kembali @MHafizAF

**Comment by escape-dev** [comment]
siap mas @tuanpembual
