### ISSUE TITLE
Feature Petugas

### ISSUE THREAD

**Issue by tuanpembual** [tuanpembual/pengaduan-masyarakat#35]
Sebagai petugas kabupaten:
- saya bisa melihat pengaduan di kabupaten saya
- saya bisa memberikan tanggapan untuk pengaduan di kabupaten saya
- (option) saya bisa mencetak semua pengaduan di kabupaten saya

**Comment by escape-dev** [comment]
### A. Sebagai petugas kabupaten hanya dapat melihat pengaduan di kabupatennya saja

1. Terdapat dua pengaduan masuk di dua daerah yang berbeda yaitu Bangka dan Belitung Timur
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/2c55eda6-cc22-46e9-a513-c85614bfc11c)

2. Untuk petugas dengan username darson112 berada pada kabupaten Bangka, ekspetasi petugas dengan username darson 112 hanya dapat melihat pengaduan di kabupaten Bangka saja
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/78b70fc5-ad40-40d3-9d4f-8d714451d606)

    Hasilnya sudah benar mas untuk username darson112 hanya dapat melihat pengaduan di kabupaten Bangka saja

**Comment by escape-dev** [comment]
### B. Sebagai petugas kabupaten hanya dapat memberikan tanggapan pada kabupatennya saja

1. Petugas mengeklik tombol "Lihat Detail"
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/60d7709a-bd91-48c2-a86d-b62c8f2a76d7)

2. Petugas memberikan tanggapan
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/1d0e2731-de67-4cbd-85c8-d7a0853bdd67)

3. Petugas dapat melihat pengaduan yang sudah di berikan tanggapan ke dalam halaman Pengaduan Proses
    ![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/eef4fa58-471c-4c37-8601-5df0ee40a6e6)

    Hasilnya sudah ok mas. Jadi untuk petugas hanya dapat memberikan tanggapan di pengaduan yang ada di kabupatennya saja.

**Comment by tuanpembual** [comment]
baik.

besok pgi saya periksa ya.
terimakasih.

**Comment by escape-dev** [comment]
Untuk bagian "saya bisa mencetak semua pengaduan di kabupaten saya" ini sudah saya buat pull request di #40 mas.

**Comment by tuanpembual** [comment]
sudah saya deploy ya. tq
