### ISSUE TITLE
Edit Tabel masyarakat

### ISSUE THREAD

**Issue by tuanpembual** [tuanpembual/pengaduan-masyarakat#48]
nik -> nik_masyarakat
id_masyarakat sbg FK

![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/922635/eded2da5-048c-428b-bd54-4f5b380d4044)

**Comment by escape-dev** [comment]
yang disini udah di fix saat benerin login buat masyarakat mas @tuanpembual
