### ISSUE TITLE
Bug: Masyarakat Belum bisa mendaftar akun.

### ISSUE THREAD

**Issue by tuanpembual** [tuanpembual/pengaduan-masyarakat#62]
error di verifikasi

![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/922635/9d545f34-4478-4323-8e27-0722d9f5d11b)

**Comment by escape-dev** [comment]
![image](https://github.com/tuanpembual/pengaduan-masyarakat/assets/75306047/4731bcc6-dbbf-48d3-aa1e-3bf79e71b300)

itu karena disini belum diganti mas sepertinya jadi engga sama yang di db. Bentar saya fix sekalian
