### ISSUE TITLE
Seputar Database

### ISSUE THREAD

**Issue by escape-dev** [tuanpembual/pengaduan-masyarakat#7]
mas @tuanpembual, ternyata kalau jadine tabel petugas di pisah di petugas_kabupaten perubahanya terlalu banyak itu.
bisa pengaruh di code yang udah ada termasuk di bagian controller dan model tanggapan. Nanti itu jadi kayak ngerubah total gitu di bagian tanggapanya. Sama flownya nanti juga berantakan mas.

**Comment by tuanpembual** [comment]
oce, lanjut via jalur cadangan td aja.

**Comment by escape-dev** [comment]
> 

Berarti aku langsung lanjut bikin tabel baru buat upload file bukti ya mas

**Comment by tuanpembual** [comment]
oce
